spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
          non_contextual_creation: true
        temp.use_jdbc_metadata_defaults: false
#          spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults = false
server:
  port: 8080