spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/GENERIC
    username: crud
    password: admin
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
          non_contextual_creation: true
          temp.use_jdbc_metadata_defaults: false
server:
  port: 8082